---

- hosts: gns3_router
  become: true
  gather_facts: no
  tasks:

    - name: Apply the provided configuration
      cisco.ios.ios_hostname:
        config:
          hostname: R1
        state: merged

    - name: Configure login banner
      cisco.ios.ios_banner:
        banner: motd
        text: |
          Authorized personnel only.
        state: present

    - name: configure line console 0
      cisco.ios.ios_config:
        lines:
        - password cisco
        - login
        - logging synchronous
        parents: line console 0

    - name: configure privilage exec mode password
      cisco.ios.ios_config:
        lines: enable secret class

    - name: save the running config to startup config
      cisco.ios.ios_config:
        save_when: modified

    - block:

      - name: checking hostname
        cisco.ios.ios_command:
          commands: show run
        register: Check_hostname

      - debug:
          msg="{{ Check_hostname }}"

    - name: configure ip address in fa0/0
      cisco.ios.ios_config:
        lines:
        - ip address 192.168.56.1 255.255.255.0
        - no shutdown
        parents: interface fa0/0

    - block:

      - name: checking hostname
        cisco.ios.ios_command:
          commands: show ip interface brief
        register: Check_Hostname

      - debug:
          msg="{{ Check_Hostname }}"
